import type {
  RentCollectionReportData,
  ResidentsListReportData,
  ResidentProfileReportData,
} from "@/types/report";
import { formatCnic } from "@/utils/cnic";
import {
  formatCurrency,
  formatMonthYear,
  formatReportDate,
  formatShortDate,
  rentStatusLabel,
} from "@/utils/reports/format";

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function imageSrc(value?: string | null) {
  if (!value) return "";
  if (value.startsWith("data:") || value.startsWith("http")) return value;
  return "";
}

const BASE_STYLES = `
  * { box-sizing: border-box; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
    color: #0A0A0A;
    margin: 0;
    padding: 32px;
    background: #fff;
  }
  .header {
    border-bottom: 3px solid #5DB7DE;
    padding-bottom: 16px;
    margin-bottom: 24px;
  }
  .brand {
    font-size: 28px;
    font-weight: 700;
    color: #5DB7DE;
    letter-spacing: 1px;
  }
  .title {
    font-size: 22px;
    font-weight: 700;
    margin: 8px 0 4px;
  }
  .meta {
    font-size: 12px;
    color: #666;
    line-height: 1.6;
  }
  .summary-grid {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 12px;
    margin: 20px 0;
  }
  .summary-card {
    border: 1px solid #E4E4E4;
    border-radius: 10px;
    padding: 12px;
    background: #F8FCFE;
  }
  .summary-label {
    font-size: 10px;
    text-transform: uppercase;
    color: #858585;
    letter-spacing: 0.6px;
    margin-bottom: 6px;
  }
  .summary-value {
    font-size: 18px;
    font-weight: 700;
    color: #0A0A0A;
  }
  .section-title {
    font-size: 16px;
    font-weight: 700;
    margin: 24px 0 10px;
    color: #0A0A0A;
  }
  table {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 20px;
    font-size: 12px;
  }
  th, td {
    border: 1px solid #E4E4E4;
    padding: 8px 10px;
    text-align: left;
    vertical-align: top;
  }
  th {
    background: #EAF6FB;
    font-weight: 700;
    color: #0A0A0A;
  }
  tr:nth-child(even) td {
    background: #FCFCFC;
  }
  .badge {
    display: inline-block;
    padding: 3px 8px;
    border-radius: 999px;
    font-size: 10px;
    font-weight: 700;
    text-transform: uppercase;
  }
  .badge-paid { background: #E6FAF2; color: #15803D; }
  .badge-pending { background: #FEF3C7; color: #B45309; }
  .badge-review { background: #EDE9FE; color: #6D28D9; }
  .footer {
    margin-top: 32px;
    padding-top: 12px;
    border-top: 1px solid #E4E4E4;
    font-size: 11px;
    color: #858585;
    text-align: center;
  }
  .profile-wrap {
    display: flex;
    gap: 24px;
    align-items: flex-start;
    margin-bottom: 24px;
  }
  .profile-photo {
    width: 120px;
    height: 120px;
    border-radius: 16px;
    object-fit: cover;
    border: 2px solid #C4E5F3;
    background: #EAF6FB;
  }
  .profile-placeholder {
    width: 120px;
    height: 120px;
    border-radius: 16px;
    border: 2px solid #C4E5F3;
    background: #EAF6FB;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 36px;
    font-weight: 700;
    color: #5DB7DE;
  }
  .detail-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 12px 24px;
    margin-bottom: 20px;
  }
  .detail-item {
    border: 1px solid #E4E4E4;
    border-radius: 10px;
    padding: 12px;
    background: #FCFCFC;
  }
  .detail-label {
    font-size: 10px;
    text-transform: uppercase;
    color: #858585;
    letter-spacing: 0.5px;
    margin-bottom: 4px;
  }
  .detail-value {
    font-size: 14px;
    font-weight: 600;
    color: #0A0A0A;
    word-break: break-word;
  }
  .id-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 16px;
    margin-top: 16px;
  }
  .id-card img {
    width: 100%;
    max-height: 180px;
    object-fit: contain;
    border: 1px solid #E4E4E4;
    border-radius: 10px;
    background: #F5F5F5;
  }
  .id-label {
    font-size: 11px;
    font-weight: 700;
    margin-bottom: 6px;
    color: #555;
  }
`;

function reportShell(title: string, metaLines: string[], body: string) {
  return `<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <style>${BASE_STYLES}</style>
  </head>
  <body>
    <div class="header">
      <div class="brand">OSSTEL</div>
      <div class="title">${escapeHtml(title)}</div>
      <div class="meta">${metaLines.map((line) => escapeHtml(line)).join("<br />")}</div>
    </div>
    ${body}
    <div class="footer">Generated by OSSTEL · Hostel Management Platform</div>
  </body>
</html>`;
}

function summaryCards(summary: {
  expected: number;
  collected: number;
  pending: number;
  review: number;
}) {
  return `
    <div class="summary-grid">
      <div class="summary-card"><div class="summary-label">Expected</div><div class="summary-value">${formatCurrency(summary.expected)}</div></div>
      <div class="summary-card"><div class="summary-label">Collected</div><div class="summary-value">${formatCurrency(summary.collected)}</div></div>
      <div class="summary-card"><div class="summary-label">Pending</div><div class="summary-value">${formatCurrency(summary.pending)}</div></div>
      <div class="summary-card"><div class="summary-label">Under Review</div><div class="summary-value">${formatCurrency(summary.review)}</div></div>
    </div>
  `;
}

function statusBadge(status: string) {
  const label = rentStatusLabel(status);
  const cls =
    status === "paid"
      ? "badge-paid"
      : status === "review"
        ? "badge-review"
        : "badge-pending";
  return `<span class="badge ${cls}">${escapeHtml(label)}</span>`;
}

export function buildRentCollectionHtml(data: RentCollectionReportData) {
  const sectionsHtml = data.sections
    .map((section) => {
      const rows =
        section.records.length > 0
          ? section.records
              .map(
                (record) => `
              <tr>
                <td>${escapeHtml(record.resident.name)}</td>
                <td>${escapeHtml(record.resident.phone)}</td>
                <td>${escapeHtml(record.room.roomNumber)}</td>
                <td>${formatCurrency(record.amount)}</td>
                <td>${statusBadge(record.status)}</td>
                <td>${record.isOverdue ? "Yes" : "No"}</td>
              </tr>
            `,
              )
              .join("")
          : `<tr><td colspan="6">No rent records for this period.</td></tr>`;

      return `
        <div class="section-title">${escapeHtml(section.hostelName)}</div>
        ${summaryCards(section.summary)}
        <table>
          <thead>
            <tr>
              <th>Resident</th>
              <th>Phone</th>
              <th>Room</th>
              <th>Amount</th>
              <th>Status</th>
              <th>Overdue</th>
            </tr>
          </thead>
          <tbody>${rows}</tbody>
        </table>
      `;
    })
    .join("");

  const body = `
    ${summaryCards(data.totals)}
    ${sectionsHtml}
  `;

  return reportShell("Monthly Rent Collection Report", [
    `Period: ${formatMonthYear(data.month, data.year)}`,
    `Scope: ${data.scopeLabel}`,
    `Generated: ${formatReportDate(data.generatedAt)}`,
    `Prepared by: ${data.generatedBy}`,
  ], body);
}

export function buildResidentsListHtml(data: ResidentsListReportData) {
  const rows =
    data.residents.length > 0
      ? data.residents
          .map(
            (resident) => `
          <tr>
            <td>${escapeHtml(resident.name)}</td>
            <td>${escapeHtml(resident.phone)}</td>
            <td>${escapeHtml(resident.roomNumber)}</td>
            <td>${escapeHtml(resident.hostelName)}</td>
            <td>${escapeHtml(resident.cnic ? formatCnic(resident.cnic) : "—")}</td>
            <td>${escapeHtml(resident.emergencyNumber ?? "—")}</td>
            <td>${escapeHtml(formatShortDate(resident.checkInDate))}</td>
            <td>${escapeHtml(resident.status)}</td>
          </tr>
        `,
          )
          .join("")
      : `<tr><td colspan="8">No residents found for this scope.</td></tr>`;

  const body = `
    <div class="summary-grid">
      <div class="summary-card"><div class="summary-label">Total Residents</div><div class="summary-value">${data.residents.length}</div></div>
    </div>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Phone</th>
          <th>Room</th>
          <th>Hostel</th>
          <th>CNIC</th>
          <th>Emergency</th>
          <th>Check-in</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>${rows}</tbody>
    </table>
  `;

  return reportShell("Residents Directory Report", [
    `Scope: ${data.scopeLabel}`,
    `Generated: ${formatReportDate(data.generatedAt)}`,
    `Prepared by: ${data.generatedBy}`,
  ], body);
}

export function buildResidentProfileHtml(data: ResidentProfileReportData) {
  const photo = imageSrc(data.profileImage);
  const initials = data.name
    .split(" ")
    .filter(Boolean)
    .slice(0, 2)
    .map((part) => part[0]?.toUpperCase() ?? "")
    .join("");

  const photoHtml = photo
    ? `<img class="profile-photo" src="${photo}" alt="Profile" />`
    : `<div class="profile-placeholder">${escapeHtml(initials || "VA")}</div>`;

  const cnicFront = imageSrc(data.cnicFront);
  const cnicBack = imageSrc(data.cnicBack);

  const idSection =
    cnicFront || cnicBack
      ? `
      <div class="section-title">CNIC Documents</div>
      <div class="id-grid">
        ${
          cnicFront
            ? `<div class="id-card"><div class="id-label">CNIC Front</div><img src="${cnicFront}" alt="CNIC Front" /></div>`
            : ""
        }
        ${
          cnicBack
            ? `<div class="id-card"><div class="id-label">CNIC Back</div><img src="${cnicBack}" alt="CNIC Back" /></div>`
            : ""
        }
      </div>
    `
      : "";

  const body = `
    <div class="profile-wrap">
      ${photoHtml}
      <div style="flex:1">
        <div class="section-title" style="margin-top:0">${escapeHtml(data.name)}</div>
        <div class="meta">
          ${escapeHtml(data.hostelName)} · Room ${escapeHtml(data.roomNumber)}<br />
          Status: ${escapeHtml(data.status)} · Check-in: ${escapeHtml(formatShortDate(data.checkInDate))}
        </div>
      </div>
    </div>

    <div class="detail-grid">
      <div class="detail-item"><div class="detail-label">Phone</div><div class="detail-value">${escapeHtml(data.phone)}</div></div>
      <div class="detail-item"><div class="detail-label">CNIC</div><div class="detail-value">${escapeHtml(data.cnic ? formatCnic(data.cnic) : "Not provided")}</div></div>
      <div class="detail-item"><div class="detail-label">Emergency Contact</div><div class="detail-value">${escapeHtml(data.emergencyNumber ?? "Not provided")}</div></div>
      <div class="detail-item"><div class="detail-label">Father Name</div><div class="detail-value">${escapeHtml(data.fatherName ?? "Not provided")}</div></div>
      <div class="detail-item"><div class="detail-label">Father Phone</div><div class="detail-value">${escapeHtml(data.fatherPhone ?? "Not provided")}</div></div>
      <div class="detail-item"><div class="detail-label">Hostel</div><div class="detail-value">${escapeHtml(data.hostelName)}</div></div>
      <div class="detail-item"><div class="detail-label">Hostel Address</div><div class="detail-value">${escapeHtml(data.hostelAddress ?? "—")}${data.hostelCity ? `, ${escapeHtml(data.hostelCity)}` : ""}</div></div>
      <div class="detail-item"><div class="detail-label">Hostel Contact</div><div class="detail-value">${escapeHtml(data.hostelContactPhone ?? "—")}</div></div>
    </div>
    ${idSection}
  `;

  return reportShell("Resident Profile Report", [
    `Resident: ${data.name}`,
    `Generated: ${formatReportDate(data.generatedAt)}`,
    `Prepared by: ${data.generatedBy}`,
  ], body);
}

export interface ResidentRentHistoryReportData {
  year: number;
  residentName: string;
  hostelName: string;
  roomNumber: string;
  generatedAt: string;
  records: Array<{
    month: number;
    year: number;
    amount: number;
    status: string;
  }>;
  summary: {
    totalPaid: number;
    monthsPaid: number;
    monthsPending: number;
  };
}

export function buildResidentRentHistoryHtml(data: ResidentRentHistoryReportData) {
  const rows =
    data.records.length > 0
      ? data.records
          .map((record) => {
            const monthLabel = formatMonthYear(record.month, record.year);
            return `
              <tr>
                <td>${escapeHtml(monthLabel)}</td>
                <td>${formatCurrency(record.amount)}</td>
                <td>${escapeHtml(rentStatusLabel(record.status))}</td>
              </tr>
            `;
          })
          .join("")
      : `<tr><td colspan="3">No rent records for ${data.year}.</td></tr>`;

  const body = `
    <div class="summary-grid">
      <div class="summary-card"><div class="summary-label">Total Paid</div><div class="summary-value">${formatCurrency(data.summary.totalPaid)}</div></div>
      <div class="summary-card"><div class="summary-label">Months Paid</div><div class="summary-value">${data.summary.monthsPaid}</div></div>
      <div class="summary-card"><div class="summary-label">Pending Months</div><div class="summary-value">${data.summary.monthsPending}</div></div>
    </div>
    <table>
      <thead>
        <tr>
          <th>Month</th>
          <th>Amount</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>${rows}</tbody>
    </table>
  `;

  return reportShell("My Rent Payment Report", [
    `Resident: ${data.residentName}`,
    `Hostel: ${data.hostelName} · Room ${data.roomNumber}`,
    `Year: ${data.year}`,
    `Generated: ${formatReportDate(data.generatedAt)}`,
  ], body);
}
